# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build and push image
    jobs:
      - job: Build
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'Docker Hub'
              repository: 'victorb96/gf-controle-acesso'
              command: 'buildAndPush'
              Dockerfile: './Dockerfile'
              buildContext: '.'
              tags: |
                $(Build.BuildId)
                latest
  - stage: RELEASE
    dependsOn: [Build]
    jobs:
      - job: Deploy
        steps:
          - script: echo Deploy RELEASE
